spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:frogcrew
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email-username}
    password: ${email-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
api:
  endpoint:
    base-url: /api/v1
